import{a as x,S as p,i as l}from"./assets/vendor-BjRz3xa9.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function t(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=t(r);fetch(r.href,o)}})();const E="49366539-6fd412d088ca04dcc1c9b4bd7";let M=15;const h=async(e,a)=>{try{return(await x.get("https://pixabay.com/api/",{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:M,page:a}})).data}catch(t){return console.error("Error fetching images:",t),[]}};let c=new p(".gallery a",{captionsData:"alt",captionDelay:250});function b(){const e=document.querySelector(".loader");e&&(e.style.display="inline-block")}function u(){const e=document.querySelector(".loader");e&&(e.style.display="none")}const P=()=>{const e=document.querySelector(".gallery");e.innerHTML="",m()};function S(e){document.querySelector(".gallery").insertAdjacentHTML("beforeend",e.map(({webformatURL:t,largeImageURL:i,tags:r,likes:o,views:s,comments:q,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${t}" alt="${r}" loading="lazy" />
        </a>
        <div class="info">
                <p><b>Likes</b><br>${o}</p>
                <p><b>Views</b><br>${s}</p>
                <p><b>Comments</b><br>${q}</p>
                <p><b>Downloads</b><br>${v}</p>
            </div>
      </li>`).join("")),c.refresh()}function w(){c||(c=new p(".gallery a",{captionsData:"alt",captionDelay:250})),c.refresh()}function m(){const e=document.querySelector(".gallery-item");if(e){const a=e.getBoundingClientRect().height;window.scrollBy({top:a*2,left:0,behavior:"smooth"})}}function L(){const e=document.querySelector(".load-more");e&&(e.style.display="flex")}function n(){const e=document.querySelector(".load-more");e&&(e.style.display="none")}const y=document.querySelector(".form");let f=1,d="";u();n();y.addEventListener("submit",async function(e){e.preventDefault();const a=y.querySelector('input[name="search-text"]').value.trim();if(!a){l.error({title:"Error",message:"Please, enter the text for search!"});return}a!==d&&(f=1,P(),m(),d=a),b(),n();try{const t=await h(d,f);if(u(),!t||!t.hits||t.hits.length===0){l.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!"}),n();return}const i=t.hits;S(i),w(),L()}catch(t){n(),l.error({title:"Error",message:"Illegal operation."}),n(),console.error(t)}});const g=document.querySelector(".load-more");g&&g.addEventListener("click",async()=>{f+=1,b();try{const e=await h(d,f);if(u(),n(),!e||!e.hits||e.hits.length===0){l.warning({title:"Caution",message:"Sorry, no more images available."}),n();return}else L();S(e.hits),w(),m()}catch(e){u(),l.error({title:"Error",message:"Error loading more images."}),n(),console.error(e)}});
//# sourceMappingURL=index.js.map
