import{a as d,S as u,i}from"./assets/vendor-BjRz3xa9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();const f="49366539-6fd412d088ca04dcc1c9b4bd7",y=async e=>{try{return await d.get("https://pixabay.com/api/",{params:{key:f,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}})}catch(t){throw console.error("Error fetching images:",t),t}};function p(){const e=document.querySelector(".loader");e&&(e.style.display="inline-block")}function l(){const e=document.querySelector(".loader");e&&(e.style.display="none")}const m=()=>{let e=document.querySelector(".gallery");e&&(e.innerHTML="")};function g(e){const t=document.querySelector(".gallery");e.forEach(o=>{const s=document.createElement("li");s.classList.add("gallery-item"),s.innerHTML=`
            <a href="${o.largeImageURL}"><img src="${o.webformatURL}" alt="${o.tags}"></a>
            <div class="info">
                <p><b>Likes</b><br>${o.likes}</p>
                <p><b>Views</b><br>${o.views}</p>
                <p><b>Comments</b><br>${o.comments}</p>
                <p><b>Downloads</b><br>${o.downloads}</p>
            </div>
        `,t.appendChild(s)})}function h(){new u(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function b(){const e=document.querySelector(".load-more");e&&(e.style.display="none")}const c=document.querySelector(".form");l();b();c.addEventListener("submit",async function(e){e.preventDefault();const t=c.querySelector('input[name="search-text"]').value.trim();if(!t){i.error({title:"Error",message:"Please, enter the text for search!"});return}p();let o=document.querySelector(".gallery");o?m():o=createGallery();try{const s=await y(t);l();const r=s.data.hits;if(r.length===0){i.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(r),h()}catch(s){l(),i.error({title:"Error",message:"Illegal operation."}),console.error(s)}});
//# sourceMappingURL=index.js.map
