import{a as u,S as d,i}from"./assets/vendor-DEZpR2tN.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const f="49366539-6fd412d088ca04dcc1c9b4bd7",m=t=>u.get("https://pixabay.com/api/",{params:{key:f,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}});function p(){const t=document.querySelector(".loader");t&&(t.style.display="inline-block")}function l(){const t=document.querySelector(".loader");t&&(t.style.display="none")}const y=()=>{let t=document.querySelector(".gallery");t&&(t.innerHTML="")};function g(t){const a=document.querySelector(".gallery");t.forEach(r=>{const n=document.createElement("li");n.classList.add("gallery-item"),n.innerHTML=`
            <a href="${r.largeImageURL}"><img src="${r.webformatURL}" alt="${r.tags}"></a>
            <div class="info">
                <p><b>Likes</b><br>${r.likes}</p>
                <p><b>Views</b><br>${r.views}</p>
                <p><b>Comments</b><br>${r.comments}</p>
                <p><b>Downloads</b><br>${r.downloads}</p>
            </div>
        `,a.appendChild(n)})}function h(){new d(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const c=document.querySelector(".form");l();c.addEventListener("submit",function(t){t.preventDefault();const a=c.querySelector('input[name="search-text"]').value.trim();if(!a){i.error({title:"Error",message:"Please, enter the text for search!"});return}p();let r=document.querySelector(".gallery");r?y():r=createGallery(),m(a).then(n=>{l();const e=n.data.hits;if(e.length===0){i.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(e),h()}).catch(n=>{l(),i.error({title:"Error",message:"Illegal operation."}),console.error(n)})});
//# sourceMappingURL=index.js.map
